# Generated by Django 3.2.13 on 2022-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=3, upload_to='book_img/'),
            preserve_default=False,
        ),
    ]
